# Generated by Django 5.1.4 on 2025-01-08 11:19

import colorful.fields
import django.db.models.deletion
import djangocms_text_ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEventsModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('event_day', models.CharField(max_length=1000)),
                ('event_date', models.CharField(max_length=1000)),
                ('event_title', models.CharField(max_length=1000)),
                ('event_time', models.CharField(max_length=1000)),
                ('event_description', djangocms_text_ckeditor.fields.HTMLField(max_length=1000)),
                ('event_font_color', colorful.fields.RGBColorField(blank=True, default='#fff', help_text='Choose the desired font color.', verbose_name='Font Color')),
                ('event_card_shadow_color', colorful.fields.RGBColorField(blank=True, default='#fff', help_text='Choose the desired Shadow color.', verbose_name='Shadow Color')),
                ('event_card_color', colorful.fields.RGBColorField(blank=True, default='#fff', help_text='Choose the desired Card color.', verbose_name='Card Color')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='media/events_images')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
