# Generated by Django 5.1.4 on 2025-01-13 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckBoxFieldPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(help_text='Used to set the field name', max_length=255)),
                ('is_required', models.BooleanField(default=False, verbose_name='Field is required')),
                ('default', models.BooleanField(default=False, help_text='Check this box to have the checkbox pre-checked by default', verbose_name='Default')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='DateTimeFieldPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(help_text='Used to set the field name', max_length=255)),
                ('is_required', models.BooleanField(default=False, verbose_name='Field is required')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='DropdownPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(help_text='Used to set the field name', max_length=255)),
                ('placeholder_text', models.CharField(blank=True, help_text='Default text in a form. Disappears when the user starts typing. Example: "email@example.com"', max_length=255, null=True, verbose_name='Placeholder Text')),
                ('is_required', models.BooleanField(default=False, verbose_name='Field is required')),
                ('values', models.JSONField(default=list, help_text='Enter multiple values for the dropdown')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='EmailFieldPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(help_text='Used to set the field name', max_length=255)),
                ('placeholder_text', models.CharField(blank=True, help_text='Default text in a form. Disappears when the user starts typing. Example: "email@example.com"', max_length=255, null=True, verbose_name='Placeholder Text')),
                ('is_required', models.BooleanField(default=False, verbose_name='Field is required')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FormPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('form_name', models.CharField(max_length=255, verbose_name='Form Name')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='LocationFieldPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(help_text='Used to set the field name', max_length=255)),
                ('is_required', models.BooleanField(default=False, verbose_name='Field is required')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='MarketingFieldPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('is_required', models.BooleanField(default=False, verbose_name='Field is required')),
                ('default_location', models.IntegerField(blank=True, help_text='The marketing location selected from the list', null=True, verbose_name='Selected Location')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NumberFieldPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(help_text='Used to set the field name', max_length=255)),
                ('placeholder_text', models.CharField(blank=True, help_text='Default text in a form. Disappears when the user starts typing. Example: "email@example.com"', max_length=255, null=True, verbose_name='Placeholder Text')),
                ('is_required', models.BooleanField(default=False, verbose_name='Field is required')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PhoneNumberFieldPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(help_text='Used to set the field name', max_length=255)),
                ('placeholder_text', models.CharField(blank=True, help_text='Default text in a form. Disappears when the user starts typing. Example: "email@example.com"', max_length=255, null=True, verbose_name='Placeholder Text')),
                ('is_required', models.BooleanField(default=False, verbose_name='Field is required')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TextAreaFieldPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(help_text='Used to set the field name', max_length=255)),
                ('placeholder_text', models.CharField(blank=True, help_text='Default text in a form. Disappears when the user starts typing. Example: "email@example.com"', max_length=255, null=True, verbose_name='Placeholder Text')),
                ('is_required', models.BooleanField(default=False, verbose_name='Field is required')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TextFieldPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(help_text='Used to set the field name', max_length=255)),
                ('placeholder_text', models.CharField(blank=True, help_text='Default text in a form. Disappears when the user starts typing. Example: "email@example.com"', max_length=255, null=True, verbose_name='Placeholder Text')),
                ('is_required', models.BooleanField(default=False, verbose_name='Field is required')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
