# Generated by Django 5.1.4 on 2025-01-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicData',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('field_name', models.CharField(max_length=255)),
                ('field_value', models.CharField(max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
