# Generated by Django 5.1.4 on 2025-01-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='%(app_label)s_%(class)s', to='cms.cmsplugin')),
                ('tr_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('trainer_id', models.PositiveIntegerField(default=0)),
                ('ref_link', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('skill_id', models.PositiveIntegerField(default=0)),
                ('current_level_cd', models.CharField(default='', max_length=30)),
                ('target_level_cd', models.CharField(default='', max_length=30)),
                ('project_id', models.CharField(default='', max_length=200)),
                ('event_dt', models.DateTimeField()),
                ('event_type_cd', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=200)),
                ('user_id_arr', models.CharField(default='', max_length=5000)),
                ('status_cd', models.CharField(default='status.draft', max_length=200)),
                ('obj_cd', models.CharField(default='content.training', max_length=50)),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('feedback_show_yn', models.CharField(default='Y', max_length=1)),
                ('external_survey_url', models.CharField(default='', max_length=200)),
                ('external_survey_yn', models.CharField(default='N', max_length=1)),
                ('trainer_id_arr', models.CharField(default='', max_length=5000)),
                ('show_yn', models.CharField(default='Y', max_length=1)),
                ('program_id', models.PositiveIntegerField(default=0)),
                ('module_id', models.PositiveIntegerField(default=0)),
                ('co_author_id_arr', models.CharField(default='', max_length=1000)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
